from fastapi import APIRouter
from fastapi.responses import Response
from pydantic import BaseModel
from typing import Optional
from typing import Dict
from app.core.schema import PRD
from app.services.sdlc_service import generate_architecture_from_prd
from app.services.sdlc_service import canonicalize_prd
from app.models.diagram_generator import generate_mermaid_from_architecture
from app.models.diagram_renderer import render_mermaid_to_png
from app.services.sdlc_service import generate_blueprint, generate_prd_from_blueprint, build_sprint_plan, wrap_tickets_with_adf
from app.core.jira_client import fetch_jira_metadata
from app.models.scaffold_models import SprintExecutionRequest
from app.services.sprint_executor import execute_sprint
from app.models.scaffold_models import TestGenerationRequest
from app.services.test_service import generate_and_run_tests
from app.services.github import create_pull_request, get_pr_files
router = APIRouter()


class RequirementInput(BaseModel):
    requirement: str


class ApprovalInput(BaseModel):
    blueprint: dict
    comments: Optional[str] = None


class PRDDiagramInput(BaseModel):
    prd: dict
    brd: Optional[dict] = None


PRDDiagramInput.model_rebuild()


@router.post("/sdlc/start")
def start_sdlc(req: RequirementInput):
    blueprint = generate_blueprint(req.requirement)
    return {
        "status": "BRD_GENERATED",
        "blueprint": blueprint
    }


@router.post("/sdlc/prd")
def generate_prd(data: ApprovalInput):
    prd = generate_prd_from_blueprint(data.blueprint)
    return {
        "status": "PRD_GENERATED",
        "prd": prd
    }


@router.post("/sdlc/prd/diagram")
def prd_diagram(data: PRDDiagramInput):
    canonical = canonicalize_prd(data.prd, data.brd or {})
    architecture = generate_architecture_from_prd(canonical)
    mermaid = generate_mermaid_from_architecture(architecture)
    png_bytes = render_mermaid_to_png(mermaid)
    return Response(content=png_bytes, media_type="image/png")



class SprintPlanInput(BaseModel):
    prd: dict
    project_key: str = "DEV"




@router.post("/sdlc/sprint-plan")
def generate_sprint_plan(data: SprintPlanInput):

    # Step 1: canonicalize PRD
    canonical = canonicalize_prd(data.prd, {})

    if not canonical.get('project_name'):
        canonical['project_name'] = 'SYSTEM'
    
    

    # Step 2: generate architecture
    architecture = generate_architecture_from_prd(canonical)

    # Step 3: fetch Jira metadata internally
    jira_meta = fetch_jira_metadata(data.project_key)

    # Step 4: build sprint plan
    sprint_plan = build_sprint_plan(
    canonical,
    architecture,
    jira_meta,
    data.project_key
    )

    sprint_plan = wrap_tickets_with_adf(sprint_plan)

    return {
    "status": "SPRINT_PLAN_GENERATED",
    "sprint_plan": sprint_plan
}




@router.post("/sdlc/execute-sprint")
def execute_full_sprint(data: SprintExecutionRequest):
    return execute_sprint(data)



@router.post("/sdlc/generate-tests")
def generate_tests(data: TestGenerationRequest):
    return generate_and_run_tests(data)





@router.post("/github/create-pr")
def create_pr(data: dict):

    result = create_pull_request(
        branch=data["branch_name"],
        title=f"AI Generated: {data['ticket_id']}",
        body="Auto-generated by AI SDLC pipeline"
    )

    return {
        "pr_url": result["html_url"]
    }

@router.get("/github/pr-files/{pr_number}")
def get_pr_files_api(pr_number: int):

    files = get_pr_files(pr_number)

    return {
        "files": files
    }

@router.post("/runbook/generate")
def generate_runbook(issue_key: str):

    ticket = get_ticket(issue_key)

    plan = analyze_ticket(ticket)

    return {
        "ticket": ticket,
        "plan": plan
    }

@router.post("/runbook/execute")
def execute_runbook(ticket: dict, plan: dict):

    executor = RundeckExecutor()

    execution = executor.run(
        ticket,
        plan,
        options={
            "environment": "QA",
            "version": ticket["fixVersion"],
            "dry_run": "false"
        },
        context={}
    )

    execution_url = executor.get_execution_url(execution["id"])

    return {
        "execution_id": execution["id"],
        "execution_url": execution_url
    }