from app.models.scaffold_models import SprintExecutionRequest
from app.services.scaffold_service import generate_file_for_ticket
from app.services.git_service import push_files_to_repo

import os
import subprocess
import tempfile
import shutil
import json
import datetime


def file_exists_in_repo(repo_url: str, branch_name: str, file_path: str) -> bool:
    temp_dir = tempfile.mkdtemp()

    try:
        subprocess.run(
            ["git", "clone", "--depth", "1", "--branch", branch_name, repo_url, "."],
            cwd=temp_dir,
            capture_output=True
        )

        return os.path.exists(os.path.join(temp_dir, file_path))

    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


def inject_metadata(content: str, ticket_id: str, branch: str) -> str:
    header = f"""# ---------------------------------------
# Generated by SDLC Engine
# Ticket: {ticket_id}
# Branch: {branch}
# Generated At: {datetime.datetime.utcnow().isoformat()}Z
# ---------------------------------------

"""
    return header + content


def execute_sprint(data: SprintExecutionRequest):

    generated_files = []
    repo_snapshot = []
    data_models = {}

    manifest = {
        "branch": data.branch_name,
        "generated_at": datetime.datetime.utcnow().isoformat() + "Z",
        "artifacts": []
    }

    for ticket in data.tickets:

        preview = generate_file_for_ticket(
            ticket=ticket,
            architecture=data.architecture,
            data_models=data_models,
            repo_tree=repo_snapshot,
            generated_files=generated_files
        )

        file_path = preview["file_path"]
        original_content = preview["content"]

        # =========================
        # BOOTSTRAP MODE
        # =========================
        if data.mode == "bootstrap":
            if file_exists_in_repo(data.repo_url, data.branch_name, file_path):
                print(f"Skipping {file_path} — already exists.")
                continue

        # =========================
        # PREVIEW MODE
        # =========================
        if data.mode == "preview":
            return {
                "status": "PREVIEW_READY",
                "file_path": file_path,
                "content_hash": hash(original_content)
            }

        # =========================
        # UPDATE MODE
        # =========================
        # update allows overwrite intentionally

        content_with_metadata = inject_metadata(
            original_content,
            ticket.get("id", "UNKNOWN"),
            data.branch_name
        )

        generated_files.append({
            "file_path": file_path,
            "content": content_with_metadata
        })

        repo_snapshot.append(file_path)

        manifest["artifacts"].append({
            "ticket_id": ticket.get("id", "UNKNOWN"),
            "file_path": file_path,
            "acceptance_criteria": ticket.get("acceptance_criteria", []),
            "generated_at": datetime.datetime.utcnow().isoformat() + "Z"
        })

    # Nothing generated
    if not generated_files:
        return {
            "status": "NO_CHANGES",
            "tickets_processed": len(data.tickets),
            "files_generated": 0,
            "git_status": "SKIPPED_ALL_EXISTING"
        }

    # Add manifest as tracked artifact
    generated_files.append({
        "file_path": "sdlc_manifest.json",
        "content": json.dumps(manifest, indent=2)
    })

    push_response = push_files_to_repo(
        repo_url=data.repo_url,
        branch_name=data.branch_name,
        files=generated_files,
        commit_message=f"Sprint execution ({data.mode}) auto-commit"
    )

    return {
        "status": "SPRINT_EXECUTED",
        "mode": data.mode,
        "tickets_processed": len(data.tickets),
        "files_generated": len(generated_files),
        "git_status": push_response
    }