# ---------------------------------------
# Generated by SDLC Engine
# Ticket: DEV-102
# Branch: feature/test-bootstrap-1
# Generated At: 2026-03-04T10:38:33.122918Z
# ---------------------------------------

# ---------------------------------------
# Generated by SDLC Engine
# Ticket: DEV-101
# Branch: feature/test-bootstrap-1
# Generated At: 2026-03-04T10:38:30.245524Z
# ---------------------------------------

from fastapi import FastAPI

app = FastAPI()

@app.get("/health")
async def health():
    return {"status": "ok"}

# TODO: Return service metadata (e.g., name, version)
@app.get("/status")
async def status():
    return {"service": "my_service", "version": "1.0.0"}
